### PR TITLE
Added Status to the Customer Order

### LINKED ISSUE #9: Estimated Time Arrival

### PR DESCRIPTION
**Pull request by mahithedula**
Added Status to the Customer Orders Page and a corresponding ETA. 

Fixes #9. We regressed on it in an earlier Sprint.

### CODE REVIEW

**Review by JunTaoLuo — APPROVED** [review]
This is why we need tests 😄

**Review by Joseph-ljx — APPROVED** [review]
Good changes on the eta

**Review by Bwillia2 — APPROVED** [review]
Great addition to round out the mvp!

**Comment by OpheliaLjh** [comment]
This is a well-organized PR, I like the way you format the codes

**Review by OpheliaLjh — APPROVED** [review]

**Pull request merged**
